name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Run Jest tests"]
    types: [completed]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: true
        default: 'Manual deployment trigger'

permissions: {}

jobs:
  notify-test-failure:
    permissions: {}
    if: github.event_name == 'workflow_run' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main' && github.event.workflow_run.conclusion != 'success'
    runs-on: ubuntu-latest
    steps:
    - name: Notify Discord about failed tests
      run: |
        curl https://discord.com/api/webhooks/${{ secrets.DISCORD_WEBHOOK_ID }}/${{ secrets.DISCORD_WEBHOOK_TOKEN }} -H "Content-Type: application/json" -d '{"content": ":x: Deployment skipped because Jest tests failed on main. Workflow: ${{ github.event.workflow_run.html_url }}"}'

  deploy:
    permissions: {}
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2
      run: |
        curl https://discord.com/api/webhooks/${{ secrets.DISCORD_WEBHOOK_ID }}/${{ secrets.DISCORD_WEBHOOK_TOKEN }} -H "Content-Type: application/json" -d '{"content": ":hourglass: Deployment started for main branch after tests passed - building Docker image and starting container, one moment..."}'
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key
        chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.EC2_HOST }} '
          cd /home/ubuntu
          rm -rf DevEx-Despatch-API
          git clone https://oauth2:${{ secrets.REPOSITORY_TOKEN }}@github.com/thomas-abbott05/DevEx-Despatch-API.git
          cd DevEx-Despatch-API
          printf "%s" "${{ secrets.ENV_FILE }}" > .env
          docker image prune -f
          docker build --no-cache -t devex-despatch-api .
          docker stop devex-despatch-api || true
          docker rm devex-despatch-api || true
          docker run -d -p 80:80 -p 443:443 --restart unless-stopped \
            -v /etc/letsencrypt:/etc/letsencrypt:ro \
            --name devex-despatch-api devex-despatch-api
        '
        curl https://discord.com/api/webhooks/${{ secrets.DISCORD_WEBHOOK_ID }}/${{ secrets.DISCORD_WEBHOOK_TOKEN }} -H "Content-Type: application/json" -d '{"content": ":white_check_mark: **Successfully deployed changes to AWS EC2 instance.** Newest API version now live at: ${{ vars.EC2_WEB_URL }}"}'
