name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2
      run: |
        curl https://discord.com/api/webhooks/${{ secrets.DISCORD_WEBHOOK_ID }}/${{ secrets.DISCORD_WEBHOOK_TOKEN }} -H "Content-Type: application/json" -d '{"content": "[1/4] :warning: Automatic deployment starting - deploying commit $GITHUB_SHA - connecting to EC2 instance..."}'
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key
        chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.EC2_HOST }} '
          cd /home/ubuntu
          curl https://discord.com/api/webhooks/${{ secrets.DISCORD_WEBHOOK_ID }}/${{ secrets.DISCORD_WEBHOOK_TOKEN }} -H "Content-Type: application/json" -d '{"content": "[2/4] :hourglass: Cloning repository on EC2 instance..."}'
          rm -rf DevEx-Despatch-API
          git clone https://oauth2:${{ secrets.REPOSITORY_TOKEN }}@github.com/thomas-abbott05/DevEx-Despatch-API.git
          cd DevEx-Despatch-API
          curl https://discord.com/api/webhooks/${{ secrets.DISCORD_WEBHOOK_ID }}/${{ secrets.DISCORD_WEBHOOK_TOKEN }} -H "Content-Type: application/json" -d '{"content": "[3/4] :hourglass: Building Docker image and starting container..."}'
          docker build -t devex-despatch-api .
          docker stop devex-despatch-api || true
          docker rm devex-despatch-api || true
          docker run -d -p 80:80 --restart unless-stopped --name devex-despatch-api devex-despatch-api
        '
        curl https://discord.com/api/webhooks/${{ secrets.DISCORD_WEBHOOK_ID }}/${{ secrets.DISCORD_WEBHOOK_TOKEN }} -H "Content-Type: application/json" -d '{"content": "[4/4] :white_check_mark: Successfully deployed to AWS EC2 instance. Newest API version now live!"}'
